### ISSUE TITLE
Unfair comparison

### ISSUE THREAD

**Issue by cyr-l** [burakcan/redux-shared-worker#1]
If I may, it is not very fair to compare perceived time consumed between `no worker` and `worker` versions because - although worker version seems quicker - they're not the same order of magnitude:

https://github.com/burakcan/redux-shared-worker/blob/master/demo/src/configureNonWorkerStore.js#L7
https://github.com/burakcan/redux-shared-worker/blob/master/demo/src/configureNonSharedStore.js#L9

😄

**Comment by burakcan** [comment]
Thank you @cbioley :D
The point of the demo was to show how worker one does it's job without blocking the page, looks like i forgot to change them to be equal. I think it's fair enough now :)

**Comment by cyr-l** [comment]
@burakcan Haaaa, thank you :)
