### ISSUE TITLE
Redux as peerDependency

### ISSUE THREAD

**Issue by jakubwolny** [burakcan/redux-shared-worker#3]
In my opinion redux shouldn't be a dependency of that project. If I require this into my codebase I'd have 2 versions of redux. As every other plugin-like project peerDependency should be used instead.

**Comment by burakcan** [comment]
Hi @hamczu thank you for your interest. But this repo is not meant to use, it was just an experiment and reference implementation to this kind of stuff. If you check the source, it's pretty easy to implement your own.

cheers :)

**Comment by jakubwolny** [comment]
Hi @burakcan - thanks for the fast answer. Can I ask why do you think it's not production-use ready yet? I've considering similar approach in my application and I wanted to give it a try. I'd appreciate any feedback/experience you have. Is the passing data from worker to react a bottleneck?
